name: Apply-infra

on:
  release:
    types:
      - created
  workflow_dispatch:
#   push:
#     branches:
#       - main  


jobs:
  apply-infra:
    runs-on: ubuntu-latest
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   
    - name: Terraform init
      working-directory: ./src
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
    - name: Terraform plan
      working-directory: ./src
      run: terraform plan 

    - name: Terraform Apply 
      working-directory: ./src
      run: terraform apply --auto-approve

    - name: Get EC2 Instance ID
      id: get_instance_id
      run: echo "INSTANCE_ID=$(terraform output -raw ec2_instance_id)" >> $GITHUB_ENV
      working-directory: ./src     
  