name: Deployment ansible

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  apply-infra:
    runs-on: ubuntu-latest
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   
    - name: Terraform init
      working-directory: ./src
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
    - name: Terraform plan
      working-directory: ./src
      run: terraform plan 

    - name: Terraform Apply 
      working-directory: ./src
      run: terraform apply --auto-approve
    - name: Output EC2 IP
      id: ec2_ip
      working-directory: ./src
      run: |      
        EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)
        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
        
  provisioner:
    runs-on: ubuntu-latest
    needs: [apply-infra]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
  
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add SSH private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      shell: bash

    - name: Set permissions for SSH private key
      run: chmod 600 ~/.ssh/id_rsa

    - name: Create Ansible hosts.ini
      run: |
        echo "[ec2]" > ./ansible/hosts.ini
        echo "ec2-instance ansible_host=${{ env.EC2_PUBLIC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ./ansible/hosts.ini      

  
    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ./ansible/hosts.ini ./ansible/deploy_codedeploy_agent.yml