name: Deployment Pipeline

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  apply-infra:
    runs-on: ubuntu-latest
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   
    - name: Terraform init
      working-directory: ./src
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
    - name: Terraform plan
      working-directory: ./src
      run: terraform plan 

    - name: Terraform Apply 
      working-directory: ./src
      run: terraform apply --auto-approve  

  deploy:
    runs-on: ubuntu-latest
    needs: [apply-infra]
    steps:
      - uses: actions/checkout@v2
      - name: Upload ZIP to S3
        uses: alexshively/s3-zip-upload-for-codedeploy@v1
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: s3-app-challenge01
          AWS_REGION: us-east-1
          SOURCE_MODE: ZIP
          SOURCE_PATH: ./deploy
          DEST_FILE: deploy.zip
          APPLICATION_NAME: app-challenge
          DEPLOYMENTGROUP_NAME: group-app-challenge

