name: Deployment Pipeline

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  login-aws:
    runs-on: ubuntu-latest
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Use SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}     
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   
    - name: Terraform init
      working-directory: ./src
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"

    - name: Terraform plan
      working-directory: ./src
      run: terraform plan -var="ssh_public_key=$SSH_PUBLIC_KEY" 


    - name: Terraform Apply 
      working-directory: ./src
      run: terraform apply -var="ssh_public_key=$SSH_PUBLIC_KEY" --auto-approve  